### PR TITLE
tvOS support for subspecs

### PR DESCRIPTION
**Pull request by ryanmaxwell**
Necessary for enabling tvOS support for DTCoreText

### CODE REVIEW

**Comment by odrobnik** [comment]
@ryanmaxwell please fix the conflicts so that I can merge this.

**Comment by ryanmaxwell** [comment]
@odrobnik as far as I'm aware there are no conflicts and this is ok to merge?

**Comment by odrobnik** [comment]
@ryanmaxwell Please do a pull --rebase from develop into your branch and push it.

**Comment by odrobnik** [comment]
@ryanmaxwell GitHub still seems to think that there is a conflict. So please `pull --rebase`

**Pull request merged**
