### PR TITLE
Fix SPM support

### PR DESCRIPTION
**Pull request by nostradani**
I implemented and tested the Swift PM support.
Now it creates viable targets for iOS and macOS.

Would also be nice if you could create a new release, so people can start using this

### CODE REVIEW

**Comment by odrobnik** [comment]
Awesome! How did you implement that (I am an SPM noob)? Are all pieces in one big framework?

**Comment by nostradani** [comment]
Basically yes, everything is part of a single framework/library. SPM will determine itself whether to create a static library or framework (depending on your whole setup).

What I did:
- Added macros to exclude platform specific code
- Added missing imports since prefix headers are not supported by SPM
- Created symbolic links for the public headers since SPM expects them in a specific structure

**Comment by odrobnik** [comment]
@nostradani I found when trying to switch to my repo that there's a reference to `_DTAnimatedGIFFromFile` missing. How did you resolve that on your clones?

**Comment by nostradani** [comment]
@odrobnik Yeah I stumbled across that issue myself later on when building for iOS. For some reason, the macros for the architecture didn't get set correctly, so I had to define them in the Package.swift. I think I had the issue only when building for Mac, but DTAnimatedGIFFromFile should only be available on iOS builds.
https://github.com/Cocoanetics/DTFoundation/compare/develop...nostradani:develop

**Comment by odrobnik** [comment]
I already fixed that issue by importing TargetConditionals in a lot of places.

**Pull request merged**
