### PR TITLE
Add support for app extension

### PR DESCRIPTION
**Pull request by m1entus**

### CODE REVIEW

**Comment by Cocoanetics** [comment]
This looks somewhat incomplete to me... where is `DT_APP_EXTENSIONS` defined?

**Comment by m1entus** [comment]
If you will define preprocessor macro, then this code will be skipped and app extension allow to build framework. Similar concept had AFNetworking few commits ago, but right now i see that they are marking method to be NS_EXTENSION_UNAVAILABLE_IOS("Not available in app extensions."), but in this case it is not possible. Just check AF_APP_EXTENSIONS macro in google

**Comment by Cocoanetics** [comment]
Thanks for the explanation!

**Comment by m1entus** [comment]
No problem, any date when can i expect new release on Cocoapods ?

**Comment by Cocoanetics** [comment]
I am facing the problem that the pod spec does not lint because it supports tvOS but I need to download Xcode 7.1 to successfully push it to trunk... I am hoping later today.

**Comment by m1entus** [comment]
Cool, thanks for your work!

**Comment by Cocoanetics** [comment]
@m1entus FYI: http://www.cocoanetics.com/2015/10/dtfoundation-1-7-8/

**Comment by m1entus** [comment]
Greak, thanks again, are you going to also bump DTCoreText version soon ?

**Comment by rogerly** [comment]
Is this working for you in an app extension?  I still have issues dealing with DTProgressHUDWindow since it also references [UIApplication sharedApplication]

**Comment by m1entus** [comment]
Have you defined DT_APP_EXTENSIONS as preprocessor marco in build settings?

**Comment by rogerly** [comment]
I have, and DTAsyncFileDeleter.m compiles fine, however DTProgressHUDWindow still references [UIApplication sharedApplication] so that particular class will not build properly in an extension (unless I am missing something)

**Pull request merged**
